#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Session-Memorycached
version:      1.1
version_from: lib/Apache/Session/Memorycached.pm
installdirs:  site
requires:
    Apache::Session:               0.0
    Cache::Memcached:              1.0.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
